const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const REGISTER_START = 'REGISTER_START';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILED = 'REGISTER_FAILED';
const RESET_LINK_SEND_START = 'RESET_LINK_SEND_START';
const RESET_LINK_SEND_SUCCESS = 'RESET_LINK_SEND_SUCCESS';
const RESET_LINK_SEND_FAILED = 'RESET_LINK_SEND_FAILED';
const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
const LOGOUT = 'LOGOUT';

export const authActionTypes = {
  SET_AUTH_STATUS,
  TOGGLE_LOADING,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  REGISTER_START,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  RESET_LINK_SEND_START,
  RESET_LINK_SEND_SUCCESS,
  RESET_LINK_SEND_FAILED,
  RESET_PASSWORD_START,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_FAILED,
  LOGOUT,
};

const SEARCH_START = 'SEARCH_START';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
const SEARCH_FAILED = 'SEARCH_FAILED';

export const searchActions = {
  SEARCH_START,
  SEARCH_SUCCESS,
  SEARCH_FAILED,
};

const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
const PROFILE_FETCH_FAILED = 'PROFILE_FETCH_FAILED';
const PROFILE_CLEAR = 'PROFILE_CLEAR';

export const profileActions = {
  PROFILE_FETCH_START,
  PROFILE_FETCH_SUCCESS,
  PROFILE_FETCH_FAILED,
  PROFILE_CLEAR,
};
